from manim import *

class MaarifScene(Scene):
    def construct(self):
        title = Text('Kesir Cesitleri').shift(UP*3)
        basit = MathTex(r'\frac{3}{4} \rightarrow \text{Basit Kesir}')
        self.play(Write(title), run_time=1)
        self.wait(1)
        self.play(Write(basit), run_time=2)
        self.wait(2)
        self.play(FadeOut(basit))
        bilesik = MathTex(r'\frac{5}{4} \rightarrow \text{Bilesik Kesir}').shift(UP*1)
        tamsayili = MathTex(r'1 \frac{1}{4} \rightarrow \text{Tam Sayili Kesir}').shift(DOWN*1)
        self.play(Write(bilesik), run_time=2)
        self.wait(1)
        self.play(Write(tamsayili), run_time=2)
        self.wait(2)
        self.play(FadeOut(bilesik), FadeOut(tamsayili), FadeOut(title))
        donusum_title = Text('Tam Sayili -> Bilesik').shift(UP*3)
        donusum1 = MathTex(r'2 \frac{1}{3} = \frac{2 \times 3 + 1}{3} = \frac{7}{3}')
        self.play(Write(donusum_title), run_time=1)
        self.play(Write(donusum1), run_time=3)
        self.wait(2)
        self.play(FadeOut(donusum_title), FadeOut(donusum1))
        bolme_title = Text('Bilesik -> Tam Sayili').shift(UP*3)
        dividend = MathTex('7').shift(LEFT*0.5 + UP*0.5)
        divisor = MathTex('3').shift(RIGHT*0.5 + UP*0.5)
        v_line = Line(UP*1, DOWN*0.5).move_to(ORIGIN)
        h_line = Line(ORIGIN, RIGHT*1).next_to(v_line.get_center(), RIGHT, buff=0)
        quotient = MathTex('2').next_to(h_line, DOWN, buff=0.2)
        minus_six = MathTex('-6').next_to(dividend, DOWN, buff=0.2)
        h_line_sub = Line(LEFT*1, ORIGIN).next_to(minus_six, DOWN, buff=0.1)
        remainder = MathTex('1').next_to(h_line_sub, DOWN, buff=0.2)
        result = MathTex(r'\frac{7}{3} = 2 \frac{1}{3}').shift(DOWN*2)
        self.play(Write(bolme_title), run_time=1)
        self.play(Write(dividend), Write(divisor), Create(v_line), Create(h_line), run_time=2)
        self.wait(1)
        self.play(Write(quotient), Write(minus_six), Create(h_line_sub), Write(remainder), run_time=3)
        self.wait(1)
        self.play(Write(result), run_time=2)
        self.wait(2)
        self.play(FadeOut(bolme_title), FadeOut(dividend), FadeOut(divisor), FadeOut(v_line), FadeOut(h_line), FadeOut(quotient), FadeOut(minus_six), FadeOut(h_line_sub), FadeOut(remainder), FadeOut(result))
        gorusuruz = Text('Maarif Matematik')
        self.play(Write(gorusuruz), run_time=1)
        self.wait(1)