cap1 = Text("Pizzayi 2 ye mi bolersen cok yersin 10 a mi", font_size=85)
cap1.scale_to_fit_width(7)
cap1.to_edge(UP)
self.play(FadeIn(cap1))
c1 = Circle(radius=2.0, color=WHITE)
s1 = Sector(radius=2.0, angle=PI, color=RED)
s1.move_to(c1.get_center())
g1_vis = VGroup(c1, s1)
t1 = MathTex(r"\frac{1}{2}")
t1.scale_to_fit_width(7)
g1 = VGroup(g1_vis, t1).arrange(DOWN, buff=1.0).scale(0.4)
c2 = Circle(radius=2.0, color=WHITE)
s2 = Sector(radius=2.0, angle=TAU/10, color=BLUE)
s2.move_to(c2.get_center())
g2_vis = VGroup(c2, s2)
t2 = MathTex(r"\frac{1}{10}")
t2.scale_to_fit_width(7)
g2 = VGroup(g2_vis, t2).arrange(DOWN, buff=1.0).scale(0.4)
main_group = VGroup(g1, g2).arrange(DOWN, buff=1.0)
self.play(FadeIn(main_group))
self.play(Indicate(s1))
cap2 = Text("Payda buyudukce parca kuculur", font_size=85)
cap2.scale_to_fit_width(7)
cap2.to_edge(UP)
self.play(Transform(cap1, cap2))
self.play(Indicate(s2))
cap3 = Text("1 bolu 2 kesri 1 bolu 10 dan buyuktur", font_size=85)
cap3.scale_to_fit_width(7)
cap3.to_edge(UP)
self.play(Transform(cap1, cap3))
self.play(Wiggle(t1))
self.play(Wiggle(t2))
cap4 = Text("Maarif Matematik ile mantigini kavra takipte kal", font_size=85)
cap4.scale_to_fit_width(7)
cap4.to_edge(DOWN)
self.play(FadeIn(cap4))
self.play(Indicate(cap4))
self.wait(1)